config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # get '/(:locale)' => 'layouts#application'
  # scope "/(:locale)", locale: /en|ja/ do
  #   resources :users
  #   resource :sessions
  # end
  
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  resources :microposts do
    member do
      post :retweet
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :location, allow_blank: true, length: { minimam: 1, maximum: 50 }
  has_many :microposts
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  has_many :favorites, foreign_key: 'user_id', dependent: :destroy
  has_many :favorite_microposts, through: :favorites, source: :micropost
  mount_uploader :avatar, AvatarUploader
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  def favorite(micropost)
      favorites.find_or_create_by(micropost_id: micropost.id)
  end

  def unfavorite(micropost)
      favorite = favorites.find_by(micropost_id: micropost.id)
      favorite.destroy if favorite
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show # 追加
   # @user = User.find(params[:id])
    @title = 'Micropost'
    @count = @user.microposts.count
   @microposts = @user.microposts.order(created_at: :desc).page(params[:page]).per(3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user # ここを修正
    else
      render 'new'
    end
  end

  def edit
   # @user = User.find(params[:id])
   # render 'edit'
  end

  def update
   # @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Updated your Plofile"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def followings
    @title = "followings"
    @user = User.find(params[:id])
    @users = @user.following_users
    render 'show_follow'
  end

  def followers
    @title = "followers"
    @user = User.find(params[:id]) 
    @users = @user.follower_users
    render 'show_follow'
  end

  def favorites
    @title = 'Favorites'
    @count = @user.favorite_microposts.count
   #@microposts = @user.favorite_microposts(created_at: :desc).page(params[:page]).per(3)
   @microposts = @user.favorite_microposts.order(created_at: :desc).page(params[:page]).per(3)             
    render 'show'
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :location)
  end

  def set_params
    @user = User.find(params[:id])
  end

  def correct_user
    redirect_to root_path if @user != current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<%# @users.each do |user| %>
<li id="user-<%= user.id %>">
  <%= link_to gravatar_for(user, size: 50), user %>
  <span class="user"><%= link_to user.name, user %></span>
</li>
<%# end %>

app/views/users/_user_info.html.erb
<section class="user_info">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  <div>
    <% if @user == current_user %>
      <p>e-mail&nbsp;&nbsp;<%= @user.email %></p>
    <% end %>
      <p><%= t('views.user_info.location') %>&nbsp;&nbsp;<%= @user.location.present? ? @user.location : "＜no-data＞" %></p>
  </div>
</section>
<h3>
  <%= link_to t('views.user_info.User'), @user %><br>
  <%= link_to t('views.user_info.Follow'), followings_user_path(@user) %>(<%= @user.following_users.count %>)<br>
  <%= link_to t('views.user_info.Follower'), followers_user_path(@user) %>(<%= @user.follower_users.count %>)
</h3>

app/views/users/edit.html.erb
<h1><%= t('.title') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->
      
      <%= image_tag @user.avatar.url if @user.avatar %>
      <%= f.label t('.avatar') %>
      <%= f.file_field :avatar %>
      <%= f.submit %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label t('views.users.password_confirmation') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label t('.location') %>
      <%= f.text_field :location, class: 'form-control' %>     

      <%= f.submit t('.Update my account'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1><%= t('.title') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label t('views.users.password_confirmation') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t('.submit'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <h3><%= t('views.show.Micropost') %></h3>
    <%= page_entries_info @microposts %>
    <ol class="microposts"><%= render @microposts %></ol>
    <%= paginate @microposts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <% if @users.any? %>
      <h3><%= @title %> (<%= @users.count %>)</h3>
      <ol class="users">
        <%= render @users %>
      </ol>
    <% end %>
  </div>
</div>