config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # get '/(:locale)' => 'layouts#application'
  # scope "/(:locale)", locale: /en|ja/ do
  #   resources :users
  #   resource :sessions
  # end
  
  resources :users do
    member do
      get :followings, :followers, :favorites
    end
  end
  resources :microposts do
    member do
      post :retweet
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true 
  validates :content, presence: true, length: { maximum: 140 }
  has_many :favorites, foreign_key: 'micropost_id', dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  def favorite?(user)
    favorite_users.include?(user)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc) # この行を追加
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  def retweet
    original = Micropost.find(params[:id])
    @micropost = current_user.microposts.build(original_user: original.id)
    @micropost.content = "さんのリツイート　\n #{original.content}"
      if @micropost.save
       flash[:success] = "Retweet created!"
       redirect_to current_user
      else
      redirect_to :back
      end
  end
  
  def favorite
    original = Micropost.find(params[:id])
    @micropost = current_user.microposts.build(original_user: original.id)
    @micropost.content = "＃ お気に入り　#{original.user.name}さんの投稿　\n #{original.content}"
      if @micropost.save
       flash[:success] = "Favorite created!"
       redirect_to current_user
      else
        redirect_to :back
      end
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/views/microposts/_favorite.html.erb
<%= link_to t('views.microposts.Favorite'), micropost_favorites_path(micropost),
                        method: :post, remote: true %>

app/views/microposts/_favorite_form.html.erb
<span id="favorite_form-<%= micropost.id %>">
  <% if micropost.favorite?(current_user) %>
    <%= render 'microposts/unfavorite', micropost: micropost %>
  <% else %>
    <%= render 'microposts/favorite', micropost: micropost %>
  <% end %>
</span>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <% if micropost.original_user.present? %>
      <% retweet_user = Micropost.find(micropost.original_user).user %>
      <%= link_to "##{retweet_user.name}", user_path(retweet_user) %>
    <% end %>
    <%= micropost.content %>
  </span>
  <span class="timestamp">
    <%= t('views.microposts.Posted') %> <%= time_ago_in_words(micropost.created_at) %> <%= t('views.microposts.ago.') %>
    <% if current_user == micropost.user %>
      <%= link_to t('views.microposts.delete'), micropost, method: :delete,
                                       data: { confirm: t('views.microposts.You sure?') } %>
    <% end %>
  </span>
</li>
<%= render 'microposts/retweet', micropost: micropost %>
<%= render 'microposts/favorite_form', micropost: micropost %>

app/views/microposts/_retweet.html.erb
<span>
  <% if micropost.original_user.nil? %>
    <%= link_to t('views.microposts.retweet'), retweet_micropost_path(micropost),
                         method: :post,
                         data: { confirm: "リツイートしますか?" } %>
  <% end %>
</span>

app/views/microposts/_unfavorite.html.erb
<%= link_to t('views.microposts.Unfavorite'), micropost_favorites_path(micropost),
                          method: :delete, remote: true %>